2025-05-28 19:17:10.287 UTC | INFO     | apscheduler.scheduler     | Adding job tentatively -- it will be properly scheduled when the scheduler starts
2025-05-28 19:17:10.289 UTC | INFO     | apscheduler.scheduler     | Added job "refresh_active_mission_cache" to job store "default"
2025-05-28 19:17:10.289 UTC | INFO     | apscheduler.scheduler     | Scheduler started
2025-05-28 19:17:10.289 UTC | INFO     | app.app                   | APScheduler started for background cache refresh.
2025-05-28 19:17:10.290 UTC | INFO     | app.app                   | BACKGROUND TASK: Starting proactive cache refresh for active real-time missions.
2025-05-28 19:17:10.290 UTC | INFO     | app.app                   | BACKGROUND TASK: Proactive cache refresh for active real-time missions completed.
2025-05-28 19:17:14.822 UTC | INFO     | app.app                   | Attempting remote load for power (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.844 UTC | INFO     | app.app                   | Attempting remote load for ctd (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.853 UTC | INFO     | app.app                   | Attempting remote load for weather (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.869 UTC | INFO     | app.app                   | Attempting remote load for waves (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.897 UTC | INFO     | app.app                   | Attempting remote load for vr2c (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.911 UTC | INFO     | app.app                   | Attempting remote load for solar (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.925 UTC | INFO     | app.app                   | Attempting remote load for fluorometer (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.938 UTC | INFO     | app.app                   | Attempting remote load for ais (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.950 UTC | INFO     | app.app                   | Attempting remote load for errors (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:14.964 UTC | INFO     | app.app                   | Attempting remote load for telemetry (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:15.033 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for power (m204). Will try next path.
2025-05-28 19:17:15.033 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for ctd (m204). Will try next path.
2025-05-28 19:17:15.033 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for weather (m204). Will try next path.
2025-05-28 19:17:15.033 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for waves (m204). Will try next path.
2025-05-28 19:17:15.033 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for vr2c (m204). Will try next path.
2025-05-28 19:17:15.033 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for solar (m204). Will try next path.
2025-05-28 19:17:15.043 UTC | INFO     | app.app                   | Attempting remote load for power (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.045 UTC | INFO     | app.app                   | Attempting remote load for ctd (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.057 UTC | INFO     | app.app                   | Attempting remote load for weather (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.066 UTC | INFO     | app.app                   | Attempting remote load for waves (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.085 UTC | INFO     | app.app                   | Attempting remote load for vr2c (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.099 UTC | INFO     | app.app                   | Attempting remote load for solar (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.103 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for telemetry (m204). Will try next path.
2025-05-28 19:17:15.103 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for fluorometer (m204). Will try next path.
2025-05-28 19:17:15.103 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for ais (m204). Will try next path.
2025-05-28 19:17:15.103 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for errors (m204). Will try next path.
2025-05-28 19:17:15.116 UTC | INFO     | app.app                   | Attempting remote load for telemetry (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.128 UTC | INFO     | app.app                   | Attempting remote load for fluorometer (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.144 UTC | INFO     | app.app                   | Attempting remote load for ais (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.155 UTC | INFO     | app.app                   | Attempting remote load for errors (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:15.187 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for weather (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Weather%20Records%202.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.187 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for power (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Amps%20Power%20Summary%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.187 UTC | WARNING  | app.app                   | No usable remote data found for weather (m204). Falling back to default local.
2025-05-28 19:17:15.187 UTC | INFO     | app.app                   | Attempting fallback local load for weather (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.202 UTC | INFO     | app.app                   | CACHE STORE: Storing weather for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.202 UTC | WARNING  | app.app                   | No usable remote data found for power (m204). Falling back to default local.
2025-05-28 19:17:15.202 UTC | INFO     | app.app                   | Attempting fallback local load for power (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.210 UTC | INFO     | app.app                   | CACHE STORE: Storing power for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.216 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for waves (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/GPS%20Waves%20Sensor%20Data.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.216 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for vr2c (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Vemco%20VR2c%20Status.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.216 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for ctd (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Seabird%20CTD%20Records%20with%20D.O..csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.216 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for solar (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Amps%20Solar%20Input%20Port%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.216 UTC | WARNING  | app.app                   | No usable remote data found for waves (m204). Falling back to default local.
2025-05-28 19:17:15.216 UTC | INFO     | app.app                   | Attempting fallback local load for waves (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.218 UTC | INFO     | app.app                   | CACHE STORE: Storing waves for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.218 UTC | WARNING  | app.app                   | No usable remote data found for vr2c (m204). Falling back to default local.
2025-05-28 19:17:15.218 UTC | INFO     | app.app                   | Attempting fallback local load for vr2c (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.218 UTC | INFO     | app.app                   | CACHE STORE: Storing vr2c for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.218 UTC | WARNING  | app.app                   | No usable remote data found for ctd (m204). Falling back to default local.
2025-05-28 19:17:15.218 UTC | INFO     | app.app                   | Attempting fallback local load for ctd (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.344 UTC | INFO     | app.app                   | CACHE STORE: Storing ctd for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.345 UTC | WARNING  | app.app                   | No usable remote data found for solar (m204). Falling back to default local.
2025-05-28 19:17:15.345 UTC | INFO     | app.app                   | Attempting fallback local load for solar (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.350 UTC | INFO     | app.app                   | CACHE STORE: Storing solar for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.360 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for telemetry (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Telemetry%206%20Report%20by%20WGMS%20Datetime.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.360 UTC | WARNING  | app.app                   | No usable remote data found for telemetry (m204). Falling back to default local.
2025-05-28 19:17:15.360 UTC | INFO     | app.app                   | Attempting fallback local load for telemetry (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.392 UTC | INFO     | app.app                   | CACHE STORE: Storing telemetry for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.403 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for errors (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Vehicle%20Error%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.403 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for ais (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/AIS%20Report.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.403 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for fluorometer (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/Fluorometer%20Samples%202.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:15.403 UTC | WARNING  | app.app                   | No usable remote data found for errors (m204). Falling back to default local.
2025-05-28 19:17:15.403 UTC | INFO     | app.app                   | Attempting fallback local load for errors (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.408 UTC | INFO     | app.app                   | CACHE STORE: Storing errors for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.408 UTC | WARNING  | app.app                   | No usable remote data found for ais (m204). Falling back to default local.
2025-05-28 19:17:15.408 UTC | INFO     | app.app                   | Attempting fallback local load for ais (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.416 UTC | INFO     | app.app                   | CACHE STORE: Storing ais for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:15.416 UTC | WARNING  | app.app                   | No usable remote data found for fluorometer (m204). Falling back to default local.
2025-05-28 19:17:15.416 UTC | INFO     | app.app                   | Attempting fallback local load for fluorometer (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:15.457 UTC | INFO     | app.app                   | CACHE STORE: Storing fluorometer for m204 (from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204) into cache.
2025-05-28 19:17:16.301 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for weather (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.314 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for ctd (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.345 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for solar (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.367 UTC | INFO     | app.app                   | Latitude/Longitude not provided for forecast. Attempting to infer from telemetry for mission m204.
2025-05-28 19:17:16.367 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for telemetry (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.382 UTC | INFO     | app.app                   | Inferred location for mission m204: Lat=44.4, Lon=-63.16
2025-05-28 19:17:16.382 UTC | INFO     | app.core.forecast         | Attempting to fetch general forecast from: https://api.open-meteo.com/v1/forecast for lat=44.4, lon=-63.16.
2025-05-28 19:17:16.403 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for power (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.420 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for fluorometer (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.440 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for vr2c (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.604 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for waves (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:16.604 UTC | INFO     | app.app                   | Applied outlier filtering to 'dp (deg)' for mission m204.
2025-05-28 19:17:16.624 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for telemetry (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:17.190 UTC | INFO     | app.core.forecast         | Successfully fetched general forecast data.
2025-05-28 19:17:20.850 UTC | INFO     | app.app                   | CACHE MISS (processed spectrum) or refresh for m204. Loading and processing source files.
2025-05-28 19:17:20.866 UTC | INFO     | app.app                   | Attempting remote load for wave_frequency_spectrum (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:20.866 UTC | INFO     | app.app                   | Latitude/Longitude not provided for marine forecast. Attempting to infer from telemetry for mission m204.
2025-05-28 19:17:20.866 UTC | INFO     | app.app                   | Cache hit (valid - static/local) for telemetry (m204). Returning cached data from Local (Default Fallback): C:\Users\ty225269\Documents\Python Playground\Data\m204.
2025-05-28 19:17:20.866 UTC | INFO     | app.app                   | Inferred location for marine forecast (mission m204): Lat=44.4, Lon=-63.16
2025-05-28 19:17:20.866 UTC | INFO     | app.core.forecast         | Attempting to fetch marine forecast from: https://marine-api.open-meteo.com/v1/marine for lat=44.4, lon=-63.16
2025-05-28 19:17:20.944 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for wave_frequency_spectrum (m204). Will try next path.
2025-05-28 19:17:20.947 UTC | INFO     | app.app                   | Attempting remote load for wave_frequency_spectrum (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:21.010 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for wave_frequency_spectrum (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/GPS%20Waves%20Frequency%20Spectrum.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:21.010 UTC | WARNING  | app.app                   | No usable remote data found for wave_frequency_spectrum (m204). Falling back to default local.
2025-05-28 19:17:21.010 UTC | INFO     | app.app                   | Attempting fallback local load for wave_frequency_spectrum (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:21.010 UTC | INFO     | app.core.loaders          | File not found at local path: C:\Users\ty225269\Documents\Python Playground\Data\m204\GPS Waves Frequency Spectrum.csv. Error: [Errno 2] No such file or directory: 'C:\\Users\\ty225269\\Documents\\Python Playground\\Data\\m204\\GPS Waves Frequency Spectrum.csv'
2025-05-28 19:17:21.010 UTC | INFO     | app.app                   | Fallback local file not found for wave_frequency_spectrum (m204) at C:\Users\ty225269\Documents\Python Playground\Data\m204
2025-05-28 19:17:21.010 UTC | INFO     | app.app                   | Attempting remote load for wave_energy_spectrum (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_realtime_missions
2025-05-28 19:17:21.081 UTC | INFO     | app.app                   | File not found in realtime path (expected for past missions): http://129.173.20.180:8086/output_realtime_missions/m204-SV3-1070 (C34164NS) for wave_energy_spectrum (m204). Will try next path.
2025-05-28 19:17:21.085 UTC | INFO     | app.app                   | Attempting remote load for wave_energy_spectrum (mission: m204, remote folder: m204-SV3-1070 (C34164NS)) from base: http://129.173.20.180:8086/output_past_missions
2025-05-28 19:17:21.152 UTC | WARNING  | app.app                   | Remote load attempt from http://129.173.20.180:8086/output_past_missions failed for wave_energy_spectrum (m204): Client error '404 Not Found' for url 'http://129.173.20.180:8086/output_past_missions/m204-SV3-1070%20(C34164NS)/GPS%20Waves%20Energy%20Spectrum.csv'
For more information check: https://httpstatuses.com/404
2025-05-28 19:17:21.152 UTC | WARNING  | app.app                   | No usable remote data found for wave_energy_spectrum (m204). Falling back to default local.
2025-05-28 19:17:21.152 UTC | INFO     | app.app                   | Attempting fallback local load for wave_energy_spectrum (mission: m204) from C:\Users\ty225269\Documents\Python Playground\Data
2025-05-28 19:17:21.152 UTC | INFO     | app.core.loaders          | File not found at local path: C:\Users\ty225269\Documents\Python Playground\Data\m204\GPS Waves Energy Spectrum.csv. Error: [Errno 2] No such file or directory: 'C:\\Users\\ty225269\\Documents\\Python Playground\\Data\\m204\\GPS Waves Energy Spectrum.csv'
2025-05-28 19:17:21.152 UTC | INFO     | app.app                   | Fallback local file not found for wave_energy_spectrum (m204) at C:\Users\ty225269\Documents\Python Playground\Data\m204
2025-05-28 19:17:21.152 UTC | WARNING  | app.core.processors       | Frequency spectrum DataFrame is None or empty for spectrum processing.
2025-05-28 19:17:21.161 UTC | WARNING  | app.app                   | No wave spectral records found or processed for mission m204.
2025-05-28 19:17:21.396 UTC | INFO     | app.core.forecast         | Successfully fetched marine forecast data.
2025-05-28 19:17:36.739 UTC | INFO     | app.app                   | APScheduler shut down.
2025-05-28 19:17:36.739 UTC | INFO     | apscheduler.scheduler     | Scheduler has been shut down
